import {
  AlarmClock,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Ban,
  Banknote,
  BarChart3,
  Bell,
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Camera,
  Car,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  Clipboard,
  ClipboardList,
  Clock,
  CloudUpload,
  Copy,
  Download,
  Eye,
  FileCheck,
  FileText,
  Folder,
  FolderOpen,
  Globe,
  GripVertical,
  Home,
  Hourglass,
  Image,
  Info,
  Inbox,
  Key,
  LayoutGrid,
  Link2,
  List,
  Lock,
  Mail,
  MapPin,
  MessageSquare,
  Minus,
  MoreVertical,
  Package,
  Paperclip,
  PenLine,
  Pencil,
  Phone,
  Pin,
  Plane,
  Plus,
  Printer,
  Redo2,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Smartphone,
  Sparkles,
  Square,
  SquareCheck,
  Star,
  StickyNote,
  Table2,
  Tag,
  Trash2,
  TrendingUp,
  Undo2,
  Upload,
  User,
  UserRoundCheck,
  Users,
  Wallet,
  X,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

/**
 * Icon runtime form — map emoji (JSON form) + tên lucide → lucide-react.
 * Dùng một chỗ này để sau này thêm control vẫn đồng bộ nét / size.
 */
const ICONS: Record<string, LucideIcon> = {
  '💾': Save,
  '🗑️': Trash2,
  '✏️': Pencil,
  '✅': Check,
  '❌': X,
  '➕': Plus,
  '➖': Minus,
  '＋': Plus,
  '⧉': Copy,
  '📋': Clipboard,
  '📄': FileText,
  '🔍': Search,
  '🔄': RefreshCw,
  '↩️': Undo2,
  '↪️': Redo2,
  '⬆️': ArrowUp,
  '⬇️': ArrowDown,
  '➡️': ArrowRight,
  '⬅️': ArrowLeft,
  '👁️': Eye,
  '🖨️': Printer,
  '📥': Download,
  '📤': Upload,
  '🔗': Link2,
  '📎': Paperclip,
  '📅': Calendar,
  '📆': CalendarDays,
  '🗓️': CalendarDays,
  '⏰': Clock,
  '🕐': Clock,
  '👤': User,
  '👥': Users,
  '🏢': Building2,
  '📊': BarChart3,
  '📈': TrendingUp,
  '💰': Wallet,
  '✉️': Mail,
  '📧': Mail,
  '🔔': Bell,
  '📝': StickyNote,
  '📁': Folder,
  '🗂️': FolderOpen,
  '⚙️': Settings,
  '🏠': Home,
  '📌': Pin,
  '🔒': Lock,
  '⭐': Star,
  '🆕': Sparkles,
  '✔️': CircleCheck,
  '🛑': Ban,
  '⚠️': AlertTriangle,
  '⬜': LayoutGrid,
  '📦': Package,
  '📷': Camera,
  '🖼️': Image,
  '🖼': Image,
  '💼': Briefcase,
  '🏷️': Tag,
  '📍': MapPin,
  '☎️': Phone,
  '📱': Smartphone,
  '🔑': Key,
  '✈️': Plane,
  '🌐': Globe,
  '💬': MessageSquare,
  '🚗': Car,
  '🏖️': Calendar,
  '💵': Banknote,
  '💴': Banknote,
  '💶': Banknote,
  '💷': Banknote,
  '📨': Inbox,
  '📬': Inbox,
  '📐': Table2,
  '📃': FileText,
  '📑': FileText,
  '📂': FolderOpen,
  '❓': CircleHelp,
  '❔': Info,
  'ℹ️': Info,
  '⌛': Hourglass,
  '⏳': Hourglass,
  '🖊️': PenLine,
  '🖋️': PenLine,
  '✍️': PenLine,
  '🗒️': ClipboardList,
  '⏱️': Clock,
  '🗺️': MapPin,
  '🪪': User,
  '🔖': FileText,
  '×': X,
  '✕': X,
  '▸': ChevronRight,
  '▾': ChevronDown,
  '‹': ChevronLeft,
  '›': ChevronRight,

  save: Save,
  trash: Trash2,
  trash2: Trash2,
  pencil: Pencil,
  edit: Pencil,
  check: Check,
  x: X,
  close: X,
  plus: Plus,
  minus: Minus,
  copy: Copy,
  clipboard: Clipboard,
  file: FileText,
  'file-text': FileText,
  search: Search,
  refresh: RefreshCw,
  'refresh-cw': RefreshCw,
  undo: Undo2,
  redo: Redo2,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  eye: Eye,
  printer: Printer,
  download: Download,
  upload: Upload,
  link: Link2,
  'link-2': Link2,
  paperclip: Paperclip,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  clock: Clock,
  'alarm-clock': AlarmClock,
  user: User,
  users: Users,
  building: Building2,
  'building-2': Building2,
  'bar-chart': BarChart3,
  'bar-chart-3': BarChart3,
  'trending-up': TrendingUp,
  wallet: Wallet,
  banknote: Banknote,
  mail: Mail,
  bell: Bell,
  'sticky-note': StickyNote,
  folder: Folder,
  'folder-open': FolderOpen,
  settings: Settings,
  home: Home,
  pin: Pin,
  lock: Lock,
  star: Star,
  sparkles: Sparkles,
  ban: Ban,
  'alert-triangle': AlertTriangle,
  square: Square,
  package: Package,
  'layout-grid': LayoutGrid,
  camera: Camera,
  image: Image,
  'cloud-upload': CloudUpload,
  'upload-cloud': CloudUpload,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'circle-plus': CirclePlus,
  'circle-check': CircleCheck,
  'check-circle': CircleCheck,
  layers: LayoutGrid,
  briefcase: Briefcase,
  phone: Phone,
  smartphone: Smartphone,
  'map-pin': MapPin,
  tag: Tag,
  plane: Plane,
  globe: Globe,
  'message-square': MessageSquare,
  car: Car,
  key: Key,
  send: Send,
  inbox: Inbox,
  table: Table2,
  list: List,
  help: CircleHelp,
  info: Info,
  'file-check': FileCheck,
  'clipboard-list': ClipboardList,
  'user-check': UserRoundCheck,
  hourglass: Hourglass,
  'calendar-check': CalendarCheck,
  'pen-line': PenLine,
  'circle-help': CircleHelp,
  'check-check': CheckCheck,
  'check-square': SquareCheck,
  'square-check': SquareCheck,
  'more-vertical': MoreVertical,
  more: MoreVertical,
  'grip-vertical': GripVertical,
  grip: GripVertical,
  drag: GripVertical,
};

export type FormIconProps = Omit<LucideProps, 'ref' | 'name'> & {
  /** Emoji trong form JSON, hoặc tên lucide (`calendar`, `chevron-left`). */
  name?: string | null;
  /** Nhãn control — dùng khi `name` không map được (HRM drawer). */
  hint?: string | null;
};

function lookupIconToken(raw: string): LucideIcon | undefined {
  const exact = ICONS[raw];
  if (exact) return exact;
  const key = raw.toLowerCase().replace(/\s+/g, '-');
  return ICONS[key];
}

const LABEL_ICON_RULES: { test: RegExp; icon: LucideIcon }[] = [
  { test: /chấm\s*công|timekeep|attendance|check[\s-]?in/i, icon: MapPin },
  { test: /^(thêm|add|new|insert)$/i, icon: Plus },
  { test: /chờ\s*duyệt|pending|approv/i, icon: UserRoundCheck },
  { test: /đã\s*xử\s*lý|processed|resolved/i, icon: FileCheck },
  { test: /tài liệu của bạn|your\s*doc/i, icon: FolderOpen },
  { test: /tài liệu|document/i, icon: FileText },
  { test: /đã\s*ký|signed|signature/i, icon: PenLine },
  { test: /đơn của bạn|application|request/i, icon: ClipboardList },
  { test: /booking|đặt lịch/i, icon: CalendarCheck },
  { test: /nghỉ|leave|phép|vắng/i, icon: Calendar },
  { test: /tăng\s*ca|làm\s*thêm|overtime|\bot\b/i, icon: Clock },
  { test: /giải\s*trình|quên\s*chấm|bù\s*công/i, icon: MapPin },
  { test: /bên\s*ngoài|công\s*tác|ra\s*ngoài|mission|trip/i, icon: Briefcase },
  { test: /wfh|tại\s*nhà|remote/i, icon: Home },
];

function iconFromLabel(hint?: string | null): LucideIcon | undefined {
  const n = (hint ?? '').replace(/\(\s*\d+\s*\)/g, ' ').replace(/\s+/g, ' ').trim();
  if (!n) return undefined;
  for (const rule of LABEL_ICON_RULES) {
    if (rule.test.test(n)) return rule.icon;
  }
  return undefined;
}

export function resolveFormIcon(name?: string | null, hint?: string | null): LucideIcon {
  const raw = name?.trim() ?? '';
  if (raw) {
    const hit = lookupIconToken(raw);
    if (hit && hit !== CircleHelp) return hit;
  }
  return iconFromLabel(hint) ?? (raw ? CircleHelp : LayoutGrid);
}

export function FormIcon({
  name,
  hint,
  size = 18,
  strokeWidth = 1.75,
  className,
  ...rest
}: FormIconProps) {
  const Icon = resolveFormIcon(name, hint);
  return (
    <Icon
      size={size}
      strokeWidth={strokeWidth}
      className={['form-icon', className].filter(Boolean).join(' ')}
      aria-hidden
      {...rest}
    />
  );
}
